name: Build & Publish Cronjobs Container

on:
  push:
    branches: [main]
  pull_request:

env:
  IMAGE_NAME: cronjobs-container

jobs:
  docker:
    if: contains(github.event.head_commit.message, '[build]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Check GHCR_Token secret
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_Token }}
        run: |
          if [ -z "$GHCR_TOKEN" ]; then
            echo "Error: GHCR_Token secret is missing or empty!"
            exit 1
          else
            echo "GHCR_Token secret is set."
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER_LC }}
          password: ${{ secrets.GHCR_Token }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:latest ./cronjobs

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:latest
          format: table
          exit-code: 1
          severity: CRITICAL  
          ignore-unfixed: true

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:latest
